name: ci-sample
on: 
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go: ['1.14','1.15']
jobs:
    check-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 #baixa o repositório
            - uses: actions/setup-go@v2
              with:
                go-version: ${{ matrix.go }}
            - run: cd src && go test #run quando quero usar comando
            - run: cd src && go run math.go #run quando quero usar comando
