name: ci-sample
on: [push]
jobs:
    check-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 #baixa o repositório
            - uses: actions/setup-go@v2
              with:
                go-version: '1.19'
            - name: Run tests
              run: go test #run quando quero usar comando
