name: ci-sample
on: 
  pull_request:
    branches:
      - develop
jobs:
    check-app:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go: ['1.19']
        steps:
            - uses: actions/checkout@v2 #baixa o repositório
            - uses: actions/setup-go@v2
              with:
                go-version: ${{ matrix.go }}
            - run: cd src && go test --coverprofile=coverage.out #run quando quero usar comando
            - 
              name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@v3 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
              name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: mneresc/app-test-go:latest