name: ci-sample
on: 
  pull_request:
    branches:
      - develop
jobs:
    check-app:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go: ['1.19']
        steps:
            - uses: actions/checkout@v2 #baixa o repositório
            - uses: actions/setup-go@v2
              with:
                go-version: ${{ matrix.go }}
            - run: cd src && go test #run quando quero usar comando
            - run: cd src && go run math.go #run quando quero usar comando
            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            # -
            #   name: Login to Docker Hub
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ secrets.DOCKERHUB_USERNAME }}
            #     password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
              name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                push: false
                tags: mneresc/app-test-go:latest